# Generated by Django 3.1.3 on 2020-11-26 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oracion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Palabra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=1)),
                ('oracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.oracion')),
            ],
            options={
                'ordering': ['lemma'],
            },
        ),
        migrations.AddField(
            model_name='oracion',
            name='texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juego.texto'),
        ),
    ]
